### ISSUE TITLE
Implement Swagger in backend

### ISSUE THREAD

**Issue by marttsang2** [openrice-canada/openrice-canada-backend#18]
Implement swagger to define the type of request body, query, and response

Reference:
- https://docs.nestjs.com/openapi/types-and-parameters
- https://docs.nestjs.com/openapi/introduction

**Comment by terryleung00** [comment]
the implement of the response body

**Comment by ttiimmothy** [comment]
please ignore this comment

**Comment by terryleung00** [comment]
#41
